#--create database silverpop;
use silverpop;
#-- CREATE USER spmgr IDENTIFIED BY 'silverpop';
#--grant usage on silverpop.* to spmgr@localhost identified by 'silverpop';
#--grant all privileges on silverpop.* to spmgr@localhost;

CREATE TABLE mailings (
    orgCode VARCHAR(15) NOT NULL,
    MailingId INT NOT NULL,
    ReportId INT NOT NULL,
    MailingName VARCHAR(50),
    #--SentDateTime VARCHAR(50),
    SentDateTime DATETIME,
    NumSent INT,
    NumSeeds INT,
    NumSuppressed INT,
    NumInboxMonitored INT,
    NumBounceHard INT,
    NumBounceSoft INT,
    NumUniqueOpen INT,
    NumGrossOpen INT,
    NumUniqueClick INT,
    NumGrossClick INT,
    NumUniqueAttach INT,
    NumGrossAttach INT,
    NumUniqueClickstreams INT,
    NumGrossClickstreams INT,
    NumUniqueMedia INT,
    NumGrossMedia INT,
    NumGrossAbuse INT,
    NumGrossChangeAddress INT,
    NumGrossMailBlock INT,
    NumGrossMailRestriction INT,
    NumGrossOther INT,
    NumConversions INT,
    NumConversionAmount INT,
    NumBounceHardFwd INT,
    NumBounceSoftFwd INT,
    NumConversionAmountFwd INT,
    NumAttachOpenFwd INT,
    NumClickFwd INT,
    NumUniqueForwardFwd INT,
    NumGrossForwardFwd INT,
    NumUniqueConversionsFwd INT,
    NumGrossConversionsFwd INT,
    NumUniqueClickstreamFwd INT,
    NumGrossClickstreamFwd INT,
    NumUniqueClickFwd INT,
    NumGrossClickFwd INT,
    NumUniqueAttachOpenFwd INT,
    NumGrossAttachOpenFwd INT,
    NumUniqueMediaFwd INT,
    NumGrossMediaFwd INT,
    NumUniqueOpenFwd INT,
    NumGrossOpenFwd INT,
    NumAbuseFwd INT,
    NumChangeAddressFwd INT,
    NumMailRestrictionFwd INT,
    NumMailBlockFwd INT,
    NumOtherFwd INT,
    NumSuppressedFwd INT,
    NumUnsubscribes INT,
    PRIMARY KEY (ReportId)
);